# Generated by Django 5.2.4 on 2025-07-21 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.banco')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ComisionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('empresa', 'Empresa')], max_length=10)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comisionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.comisionista')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.deposito')),
            ],
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiario', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('cuenta_cheque', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('concepto', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='AplicacionRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.deposito')),
                ('retiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.retiro')),
            ],
        ),
    ]
