# Generated by Django 5.2.4 on 2025-07-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='clabe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='cuenta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='sucursal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
