# Generated by Django 5.2.4 on 2025-07-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_banco_clabe_banco_cuenta_banco_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='RFC',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
