# Generated by Django 5.2.4 on 2025-07-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_empresa_rfc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comisionista',
            name='comisionado',
        ),
    ]
